// const data = {
//     code: 'ERR_BAD_REQUEST',
//     config: {
//       transitional: {
//         silentJSONParsing: true,
//         forcedJSONParsing: true,
//         clarifyTimeoutError: false
//       },
//       adapter: [ 'xhr', 'http' ],
//       transformRequest: [ [Function: transformRequest] ],
//       transformResponse: [ [Function: transformResponse] ],
//       timeout: 0,
//       xsrfCookieName: 'XSRF-TOKEN',
//       xsrfHeaderName: 'X-XSRF-TOKEN',
//       maxContentLength: -1,
//       maxBodyLength: -1,
//       env: { FormData: [Function], Blob: [class Blob] },
//       validateStatus: [Function: validateStatus],
//       headers: Object [AxiosHeaders] {
//         Accept: 'application/json, text/plain, */*',
//         'Content-Type': 'application/json',
//         'User-Agent': 'axios/1.6.7',
//         'Content-Length': '486',
//         'Accept-Encoding': 'gzip, compress, deflate, br'
//       },
//       method: 'post',
//       url: 'http://localhost:6333/collections/ayye/points',
//       data: '{"points":[{"id":1,"vector":[0.1,0.2,0.3,0.4],"payload":{"city":"London","color":"green"}},{"id":2,"vector":[0.2,0.3,0.4,0.5],"payload":{"city":"London","color":"red"}},{"id":3,"vector":[0.3,0.4,0.5,0.6],"payload":{"city":"London","color":"blue"}},{"id":4,"vector":[0.4,0.5,0.6,0.7],"payload":{"city":"Berlin","color":"red"}},{"id":5,"vector":[0.5,0.6,0.7,0.8],"payload":{"city":"Moscow","color":"green"}},{"id":6,"vector":[0.6,0.7,0.8,0.9],"payload":{"city":"Moscow","color":"blue"}}]}'
//     },
//     request: <ref *1> ClientRequest {
//       _events: [Object: null prototype] {
//         abort: [Function (anonymous)],
//         aborted: [Function (anonymous)],
//         connect: [Function (anonymous)],
//         error: [Function (anonymous)],
//         socket: [Function (anonymous)],
//         timeout: [Function (anonymous)],
//         finish: [Function: requestOnFinish]
//       },
//       _eventsCount: 7,
//       _maxListeners: undefined,
//       outputData: [],
//       outputSize: 0,
//       writable: true,
//       destroyed: true,
//       _last: false,
//       chunkedEncoding: false,
//       shouldKeepAlive: true,
//       maxRequestsOnConnectionReached: false,
//       _defaultKeepAlive: true,
//       useChunkedEncodingByDefault: true,
//       sendDate: false,
//       _removedConnection: false,
//       _removedContLen: false,
//       _removedTE: false,
//       strictContentLength: false,
//       _contentLength: '486',
//       _hasBody: true,
//       _trailer: '',
//       finished: true,
//       _headerSent: true,
//       _closed: true,
//       socket: Socket {
//         connecting: false,
//         _hadError: false,
//         _parent: null,
//         _host: 'localhost',
//         _closeAfterHandlingError: false,
//         _events: [Object],
//         _readableState: [ReadableState],
//         _writableState: [WritableState],
//         allowHalfOpen: false,
//         _maxListeners: undefined,
//         _eventsCount: 6,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: null,
//         _server: null,
//         timeout: 5000,
//         parser: null,
//         _httpMessage: null,
//         autoSelectFamilyAttemptedAddresses: [Array],
//         [Symbol(async_id_symbol)]: -1,
//         [Symbol(kHandle)]: [TCP],
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: Timeout {
//           _idleTimeout: 5000,
//           _idlePrev: [TimersList],
//           _idleNext: [TimersList],
//           _idleStart: 2697,
//           _onTimeout: [Function: bound ],
//           _timerArgs: undefined,
//           _repeat: null,
//           _destroyed: false,
//           [Symbol(refed)]: false,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 228,
//           [Symbol(triggerId)]: 226
//         },
//         [Symbol(kBuffer)]: null,
//         [Symbol(kBufferCb)]: null,
//         [Symbol(kBufferGen)]: null,
//         [Symbol(shapeMode)]: true,
//         [Symbol(kCapture)]: false,
//         [Symbol(kSetNoDelay)]: true,
//         [Symbol(kSetKeepAlive)]: true,
//         [Symbol(kSetKeepAliveInitialDelay)]: 1,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0
//       },
//       _header: 'POST /collections/ayye/points HTTP/1.1\r\n' +
//         'Accept: application/json, text/plain, */*\r\n' +
//         'Content-Type: application/json\r\n' +
//         'User-Agent: axios/1.6.7\r\n' +
//         'Content-Length: 486\r\n' +
//         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
//         'Host: localhost:6333\r\n' +
//         'Connection: keep-alive\r\n' +
//         '\r\n',
//       _keepAliveTimeout: 0,
//       _onPendingData: [Function: nop],
//       agent: Agent {
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         defaultPort: 80,
//         protocol: 'http:',
//         options: [Object: null prototype],
//         requests: [Object: null prototype] {},
//         sockets: [Object: null prototype] {},
//         freeSockets: [Object: null prototype],
//         keepAliveMsecs: 1000,
//         keepAlive: true,
//         maxSockets: Infinity,
//         maxFreeSockets: 256,
//         scheduling: 'lifo',
//         maxTotalSockets: Infinity,
//         totalSocketCount: 1,
//         [Symbol(shapeMode)]: false,
//         [Symbol(kCapture)]: false
//       },
//       socketPath: undefined,
//       method: 'POST',
//       maxHeaderSize: undefined,
//       insecureHTTPParser: undefined,
//       joinDuplicateHeaders: undefined,
//       path: '/collections/ayye/points',
//       _ended: true,
//       res: IncomingMessage {
//         _events: [Object],
//         _readableState: [ReadableState],
//         _maxListeners: undefined,
//         socket: null,
//         httpVersionMajor: 1,
//         httpVersionMinor: 1,
//         httpVersion: '1.1',
//         complete: true,
//         rawHeaders: [Array],
//         rawTrailers: [],
//         joinDuplicateHeaders: undefined,
//         aborted: false,
//         upgrade: false,
//         url: '',
//         method: null,
//         statusCode: 400,
//         statusMessage: 'Bad Request',
//         client: [Socket],
//         _consuming: false,
//         _dumped: false,
//         req: [Circular *1],
//         _eventsCount: 4,
//         responseUrl: 'http://localhost:6333/collections/ayye/points',
//         redirects: [],
//         [Symbol(shapeMode)]: true,
//         [Symbol(kCapture)]: false,
//         [Symbol(kHeaders)]: [Object],
//         [Symbol(kHeadersCount)]: 10,
//         [Symbol(kTrailers)]: null,
//         [Symbol(kTrailersCount)]: 0
//       },
//       aborted: false,
//       timeoutCb: null,
//       upgradeOrConnect: false,
//       parser: null,
//       maxHeadersCount: null,
//       reusedSocket: true,
//       host: 'localhost',
//       protocol: 'http:',
//       _redirectable: Writable {
//         _events: [Object],
//         _writableState: [WritableState],
//         _maxListeners: undefined,
//         _options: [Object],
//         _ended: true,
//         _ending: true,
//         _redirectCount: 0,
//         _redirects: [],
//         _requestBodyLength: 486,
//         _requestBodyBuffers: [],
//         _eventsCount: 3,
//         _onNativeResponse: [Function (anonymous)],
//         _currentRequest: [Circular *1],
//         _currentUrl: 'http://localhost:6333/collections/ayye/points',
//         [Symbol(shapeMode)]: true,
//         [Symbol(kCapture)]: false
//       },
//       [Symbol(shapeMode)]: false,
//       [Symbol(kCapture)]: false,
//       [Symbol(kBytesWritten)]: 0,
//       [Symbol(kNeedDrain)]: false,
//       [Symbol(corked)]: 0,
//       [Symbol(kOutHeaders)]: [Object: null prototype] {
//         accept: [Array],
//         'content-type': [Array],
//         'user-agent': [Array],
//         'content-length': [Array],
//         'accept-encoding': [Array],
//         host: [Array]
//       },
//       [Symbol(errored)]: null,
//       [Symbol(kHighWaterMark)]: 16384,
//       [Symbol(kRejectNonStandardBodyWrites)]: false,
//       [Symbol(kUniqueHeaders)]: null
//     },
//     response: {
//       status: 400,
//       statusText: 'Bad Request',
//       headers: Object [AxiosHeaders] {
//         'transfer-encoding': 'chunked',
//         vary: 'accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
//         'content-type': 'application/json',
//         date: 'Fri, 01 Mar 2024 17:04:51 GMT'
//       },
//       config: {
//         transitional: [Object],
//         adapter: [Array],
//         transformRequest: [Array],
//         transformResponse: [Array],
//         timeout: 0,
//         xsrfCookieName: 'XSRF-TOKEN',
//         xsrfHeaderName: 'X-XSRF-TOKEN',
//         maxContentLength: -1,
//         maxBodyLength: -1,
//         env: [Object],
//         validateStatus: [Function: validateStatus],
//         headers: [Object [AxiosHeaders]],
//         method: 'post',
//         url: 'http://localhost:6333/collections/ayye/points',
//         data: '{"points":[{"id":1,"vector":[0.1,0.2,0.3,0.4],"payload":{"city":"London","color":"green"}},{"id":2,"vector":[0.2,0.3,0.4,0.5],"payload":{"city":"London","color":"red"}},{"id":3,"vector":[0.3,0.4,0.5,0.6],"payload":{"city":"London","color":"blue"}},{"id":4,"vector":[0.4,0.5,0.6,0.7],"payload":{"city":"Berlin","color":"red"}},{"id":5,"vector":[0.5,0.6,0.7,0.8],"payload":{"city":"Moscow","color":"green"}},{"id":6,"vector":[0.6,0.7,0.8,0.9],"payload":{"city":"Moscow","color":"blue"}}]}'
//       },
//       request: <ref *1> ClientRequest {
//         _events: [Object: null prototype],
//         _eventsCount: 7,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: true,
//         _last: false,
//         chunkedEncoding: false,
//         shouldKeepAlive: true,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: false,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         strictContentLength: false,
//         _contentLength: '486',
//         _hasBody: true,
//         _trailer: '',
//         finished: true,
//         _headerSent: true,
//         _closed: true,
//         socket: [Socket],
//         _header: 'POST /collections/ayye/points HTTP/1.1\r\n' +
//           'Accept: application/json, text/plain, */*\r\n' +
//           'Content-Type: application/json\r\n' +
//           'User-Agent: axios/1.6.7\r\n' +
//           'Content-Length: 486\r\n' +
//           'Accept-Encoding: gzip, compress, deflate, br\r\n' +
//           'Host: localhost:6333\r\n' +
//           'Connection: keep-alive\r\n' +
//           '\r\n',
//         _keepAliveTimeout: 0,
//         _onPendingData: [Function: nop],
//         agent: [Agent],
//         socketPath: undefined,
//         method: 'POST',
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         joinDuplicateHeaders: undefined,
//         path: '/collections/ayye/points',
//         _ended: true,
//         res: [IncomingMessage],
//         aborted: false,
//         timeoutCb: null,
//         upgradeOrConnect: false,
//         parser: null,
//         maxHeadersCount: null,
//         reusedSocket: true,
//         host: 'localhost',
//         protocol: 'http:',
//         _redirectable: [Writable],
//         [Symbol(shapeMode)]: false,
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kOutHeaders)]: [Object: null prototype],
//         [Symbol(errored)]: null,
//         [Symbol(kHighWaterMark)]: 16384,
//         [Symbol(kRejectNonStandardBodyWrites)]: false,
//         [Symbol(kUniqueHeaders)]: null
//       },
//       data: { status: [Object], time: 0 }
//     }
//   }
